<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.700" tests="13" failures="10">
  <testsuite name="Root Suite" timestamp="2023-10-19T09:53:16" tests="0" time="0.000" failures="0">
  </testsuite>
  <testsuite name="stock_trades_api_medium" timestamp="2023-10-19T09:53:16" tests="13" file="E:\backend-assessment\test\index.spec.js" time="0.695" failures="10">
    <testcase name="stock_trades_api_medium should create a new trade of buy type" time="0.080" classname="should create a new trade of buy type">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 405" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 405
    at Context.<anonymous> (test\index.spec.js:70:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -405
      +201
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should create a new trade of sell type" time="0.013" classname="should create a new trade of sell type">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 405" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 405
    at Context.<anonymous> (test\index.spec.js:77:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -405
      +201
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all the trades" time="0.066" classname="should fetch all the trades">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test\index.spec.js:85:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -404
      +200
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if the type filter value does not exist" time="0.060" classname="should fetch no trades if the type filter value does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test\index.spec.js:92:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -404
      +200
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all trades for a user" time="0.059" classname="should fetch all trades for a user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test\index.spec.js:99:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -404
      +200
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if user filter value does not exist" time="0.060" classname="should fetch no trades if user filter value does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test\index.spec.js:106:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -404
      +200
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all buy trades for a user" time="0.046" classname="should fetch all buy trades for a user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test\index.spec.js:113:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -404
      +200
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all sell trades for a user" time="0.050" classname="should fetch all sell trades for a user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test\index.spec.js:120:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -404
      +200
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch a single trade" time="0.020" classname="should fetch a single trade">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test\index.spec.js:127:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -404
      +200
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 404 if the trade ID does not exist" time="0.015" classname="should get 404 if the trade ID does not exist">
      <failure message="expected &apos;&lt;!DOCTYPE html&gt;\n&lt;html lang=&quot;en&quot;&gt;\n&lt;h…&apos; to deeply equal &apos;ID not found&apos;" type="AssertionError"><![CDATA[AssertionError: expected '<!DOCTYPE html>\n<html lang="en">\n<h…' to deeply equal 'ID not found'
    at Context.<anonymous> (test\index.spec.js:134:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      + expected - actual

      -<!DOCTYPE html>
      -<html lang="en">
      -<head>
      -<meta charset="utf-8">
      -<title>Error</title>
      -</head>
      -<body>
      -<pre>Cannot GET /trades/32323</pre>
      -</body>
      -</html>
      +ID not found
      ]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a put request to /trades/:id" time="0.018" classname="should get 405 for a put request to /trades/:id">
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a patch request to /trades/:id" time="0.016" classname="should get 405 for a patch request to /trades/:id">
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a delete request to /trades/:id" time="0.020" classname="should get 405 for a delete request to /trades/:id">
    </testcase>
  </testsuite>
</testsuites>